'use client';
import { useActionState, useState, useTransition } from 'react';
import { DV_MODE_LABELS, formatPhone, WA_STATUS_LABELS, type DvMode } from '@crm/shared';
import { FormMessage, SubmitButton, type ActionState } from '@/components/form';
import { Alert, Badge, Button, Field, Select } from '@/components/ui';
import { requestCommand, saveDmSettings, setSwitches } from '../actions';
import { setReplyApprover } from '../rule-actions';

export function LinkPanel({
  status,
  phone,
  name,
  qr,
  gatewayAlive,
}: {
  status: string;
  phone: string | null;
  name: string | null;
  qr: string | null;
  gatewayAlive: boolean;
}) {
  const [state, setState] = useState<ActionState | undefined>();
  const [pending, start] = useTransition();
  const [confirmUnlink, setConfirmUnlink] = useState(false);
  const run = (cmd: 'link' | 'logout') =>
    start(async () => {
      setConfirmUnlink(false);
      setState(await requestCommand(cmd));
    });
  const linked = status === 'connected' || status === 'disconnected' || status === 'connecting';

  return (
    <div className="space-y-4 text-sm">
      <p>
        <Badge tone={status === 'connected' ? 'ok' : status === 'waiting_for_scan' ? 'warn' : 'neutral'}>{WA_STATUS_LABELS[status] ?? status}</Badge>
        {phone ? <span className="ml-2">{formatPhone(phone)}{name ? ` · ${name}` : ''}</span> : null}
      </p>

      {!gatewayAlive ? (
        <Alert tone="warn">The gateway isn&apos;t running, so it can&apos;t link or connect. Start it first (see docs/DIGITAL_VOLUNTEER.md).</Alert>
      ) : null}

      {status === 'waiting_for_scan' && qr ? (
        <div className="space-y-2">
          {/* eslint-disable-next-line @next/next/no-img-element -- data URL generated by the gateway */}
          <img src={qr} alt="WhatsApp link QR code" width={256} height={256} className="rounded-lg bg-white p-2" />
          <ol className="list-decimal space-y-1 pl-5 text-ink-muted">
            <li>On the dedicated phone, open WhatsApp → Settings → Linked devices.</li>
            <li>Tap &quot;Link a device&quot; and scan this code.</li>
            <li>The code refreshes by itself; this page updates when linking is done.</li>
          </ol>
        </div>
      ) : null}

      <div className="flex flex-wrap gap-2">
        {!linked ? (
          <Button onClick={() => run('link')} disabled={pending || !gatewayAlive || status === 'waiting_for_scan'}>
            {status === 'waiting_for_scan' ? 'Waiting for scan…' : 'Link WhatsApp'}
          </Button>
        ) : confirmUnlink ? (
          <>
            <Button variant="danger" onClick={() => run('logout')} disabled={pending}>
              Yes, unlink this number
            </Button>
            <Button variant="ghost" onClick={() => setConfirmUnlink(false)}>
              Keep it linked
            </Button>
          </>
        ) : (
          <Button variant="secondary" onClick={() => setConfirmUnlink(true)}>
            Unlink number
          </Button>
        )}
      </div>
      {confirmUnlink ? <p className="text-ink-muted">Unlinking stops everything until someone scans a new QR code.</p> : null}
      <FormMessage state={state} />
    </div>
  );
}

export function SafetySwitches({ enabled, autoPaused }: { enabled: boolean; autoPaused: boolean }) {
  const [state, setState] = useState<ActionState | undefined>();
  const [pending, start] = useTransition();
  const flip = (e: boolean | null, p: boolean | null) => start(async () => setState(await setSwitches(e, p)));

  return (
    <div className="space-y-5 text-sm">
      <div className="flex items-start justify-between gap-4">
        <div>
          <p className="font-medium">Digital Volunteer {enabled ? 'is on' : 'is off'}</p>
          <p className="text-ink-muted">When off, nothing is read or sent - an emergency stop. The number stays linked.</p>
        </div>
        <Button variant={enabled ? 'danger' : 'primary'} onClick={() => flip(!enabled, null)} disabled={pending} className="shrink-0">
          {enabled ? 'Turn off now' : 'Turn on'}
        </Button>
      </div>
      <div className="flex items-start justify-between gap-4 border-t border-line pt-5">
        <div>
          <p className="font-medium">Automatic replies {autoPaused ? 'paused' : 'allowed'}</p>
          <p className="text-ink-muted">Pause stops the bot replying by itself in every group. Suggestions and human replies continue.</p>
        </div>
        <Button variant="secondary" onClick={() => flip(null, !autoPaused)} disabled={pending} className="shrink-0">
          {autoPaused ? 'Resume' : 'Pause'}
        </Button>
      </div>
      {state?.error ? <Alert>{state.error}</Alert> : null}
    </div>
  );
}

export function DmSettingsForm({
  mode,
  courseInfo,
  followupSync,
  sevaRequests,
}: {
  mode: DvMode;
  courseInfo: boolean;
  followupSync: boolean;
  sevaRequests: boolean;
}) {
  const [state, action] = useActionState(saveDmSettings, undefined);
  return (
    <form action={action} className="space-y-4 text-sm">
      <Field label="How direct chats are handled" htmlFor="dm_mode">
        <Select id="dm_mode" name="dm_mode" defaultValue={mode}>
          {(Object.keys(DV_MODE_LABELS) as DvMode[]).map((m) => (
            <option key={m} value={m}>
              {DV_MODE_LABELS[m]}
            </option>
          ))}
        </Select>
      </Field>
      <label className="flex items-start gap-2">
        <input type="checkbox" name="dm_course_info" defaultChecked={courseInfo} className="mt-0.5 size-4 accent-accent" />
        <span>Answer course questions (from Courses and Upcoming Programs)</span>
      </label>
      <label className="flex items-start gap-2">
        <input type="checkbox" name="dm_followup_sync" defaultChecked={followupSync} className="mt-0.5 size-4 accent-accent" />
        <span>
          Log replies from leads on the lead&apos;s timeline
          <span className="block text-ink-muted">Only when the number matches exactly one lead. Never counted as a call.</span>
        </span>
      </label>
      <label className="flex items-start gap-2">
        <input type="checkbox" name="dm_seva_requests" defaultChecked={sevaRequests} className="mt-0.5 size-4 accent-accent" />
        <span>
          Accept seva requests sent privately
          <span className="block text-ink-muted">A volunteer messages the number asking for leads. Same limits and checks as in groups.</span>
        </span>
      </label>
      <FormMessage state={state} />
      <SubmitButton>Save</SubmitButton>
    </form>
  );
}

export function ReplyApproverToggle({ id, name, hasPhone, canReply, on }: { id: string; name: string; hasPhone: boolean; canReply: boolean; on: boolean }) {
  const [error, setError] = useState<string | null>(null);
  const [pending, start] = useTransition();
  const blocked = !on && (!hasPhone || !canReply);
  return (
    <li className="flex flex-wrap items-center justify-between gap-3 px-5 py-3 text-sm">
      <div>
        <p className="font-medium">
          {name} {on ? <Badge tone="ok">Gets suggested replies on WhatsApp</Badge> : null}
        </p>
        <p className="text-xs text-ink-muted">
          {!canReply ? 'Does not have the Reply permission' : !hasPhone ? 'No phone number saved in Setu' : on ? 'Answers SEND / EDIT / SKIP on WhatsApp' : 'Approves in the inbox only'}
        </p>
        {error ? <p className="text-xs text-danger">{error}</p> : null}
      </div>
      <Button
        variant={on ? 'secondary' : 'primary'}
        disabled={pending || blocked}
        onClick={() =>
          start(async () => {
            const r = await setReplyApprover(id, !on);
            setError(r.error ?? null);
          })
        }
      >
        {on ? 'Stop' : 'Send on WhatsApp'}
      </Button>
    </li>
  );
}
